name: nixbuild-ci

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build flake
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v12
    secrets:
      nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}
    with:
      filter_builds: '.top_attr == "packages"'
#     filter_builds: '.attr == "ci-build"'

  upload:
    name: Upload flake
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v16
        with:
          nix_on_tmpfs: true
          nix_conf: |
            experimental-features = nix-command flakes

      - uses: nixbuild/nixbuild-action@v12
        with:
          nixbuild_ssh_key: ${{ secrets.NIXBUILD_SSH_KEY }}

      - name: Upload flake inputs to Cachix
        working-directory: .
        run: |
          CACHIX_AUTH_TOKEN=${{ secrets.CACHIX_AUTH_TOKEN }} nix run github:Samayel/shellscripts.nix#cachix-push-flake-inputs .

      - name: Upload flake outputs to Cachix
        working-directory: .
        run: |
          CACHIX_AUTH_TOKEN=${{ secrets.CACHIX_AUTH_TOKEN }} nix run github:Samayel/shellscripts.nix#cachix-push-flake-runtime-closure-single .#ci-publish

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Load and push docker image (shellscripts.nix:latest)
        working-directory: .
        run: |
          nix run github:Samayel/shellscripts.nix#docker-load-nix-build .#docker
          docker push quyo/shellscripts.nix:latest
